# Site settings
title: BootArchive
motto: Random Tales of Informatics Engineering
email: tbd@tbd.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bootarchive.github.io" # the base hostname & protocol for your site
twitter_username: bootarchive
github_username:  bootarchive

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
