# Dependencies
markdown:            redcarpet
highlighter:         rouge
gems:
  - jekyll-redirect-from

# Permalinks
permalink:           /blog/:title.html

# Setup
title:               'Albano Drazhi'
description:         'Personal website of Albano Drazhi, Security Software Engineer.'
url:                 https://www.albanodrazhi.me

# About/contact
author:
  name:              Albano Drazhi
  url:               https://twitter.com/aldrazhi
  email:             albano.drazhi@gmail.com

# Custom vars
version:             1.0.0
